export const ALL_CLUBS_REQUEST = "ALL_CLUBS_REQUEST";
export const ALL_CLUBS_SUCCESS = "ALL_CLUBS_SUCCESS";
export const ALL_CLUBS_FAIL = "ALL_CLUBS_FAIL";

export const GET_SINGLE_CLUB_REQUEST = "GET_SINGLE_CLUB_REQUEST";
export const GET_SINGLE_CLUB_SUCCESS = "GET_SINGLE_CLUB_SUCCESS";
export const GET_SINGLE_CLUB_FAIL = "GET_SINGLE_CLUB_FAIL";

export const GET_USER_CLUBS_REQUEST = "GET_USER_CLUBS_REQUEST";
export const GET_USER_CLUBS_SUCCESS = "GET_USER_CLUBS_SUCCESS";
export const GET_USER_CLUBS_FAIL = "GET_USER_CLUBS_FAIL";

export const REGISTER_CLUB_REQUEST = "REGISTER_CLUB_REQUEST";
export const REGISTER_CLUB_SUCCESS = "REGISTER_CLUB_SUCCESS";
export const REGISTER_CLUB_FAIL = "REGISTER_CLUB_FAIL";

export const ADMIN_DELETE_CLUB_REQUEST = "ADMIN_DELETE_CLUB_REQUEST";
export const ADMIN_DELETE_CLUB_SUCCESS = "ADMIN_DELETE_CLUB_SUCCESS";
export const ADMIN_DELETE_CLUB_FAIL = "ADMIN_DELETE_CLUB_FAIL";


export const ALL_EVENTS_REQUEST = "ALL_EVENTS_REQUEST";
export const ALL_EVENTS_SUCCESS = "ALL_EVENTS_SUCCESS";
export const ALL_EVENTS_FAIL = "ALL_EVENTS_FAIL";

export const REGISTER_EVENT_REQUEST = "REGISTER_EVENT_REQUEST";
export const REGISTER_EVENT_SUCCESS = "REGISTER_EVENT_SUCCESS";
export const REGISTER_EVENT_FAIL = "REGISTER_EVENT_FAIL";

export const ADMIN_DELETE_EVENT_REQUEST = "ADMIN_DELETE_EVENT_REQUEST";
export const ADMIN_DELETE_EVENT_SUCCESS = "ADMIN_DELETE_EVENT_SUCCESS";
export const ADMIN_DELETE_EVENT_FAIL = "ADMIN_DELETE_EVENT_FAIL";


export const GET_SINGLE_EVENT_REQUEST = "GET_SINGLE_EVENT_REQUEST";
export const GET_SINGLE_EVENT_SUCCESS = "GET_SINGLE_EVENT_SUCCESS";
export const GET_SINGLE_EVENT_FAIL = "GET_SINGLE_EVENT_FAIL";

export const GET_FEST_EVENTS_REQUEST = "GET_FEST_EVENTS_REQUEST";
export const GET_FEST_EVENTS_SUCCESS = "GET_FEST_EVENTS_SUCCESS";
export const GET_FEST_EVENTS_FAIL = "GET_FEST_EVENTS_FAIL";

export const GET_SINGLE_FEST_EVENT_REQUEST = "GET_SINGLE_FEST_EVENT_REQUEST";
export const GET_SINGLE_FEST_EVENT_SUCCESS = "GET_SINGLE_FEST_EVENT_SUCCESS";
export const GET_SINGLE_FEST_EVENT_FAIL = "GET_SINGLE_FEST_EVENT_FAIL";


export const DELETE_FEST_EVENT_REQUEST = "DELETE_FEST_EVENT_REQUEST";
export const DELETE_FEST_EVENT_SUCCESS = "DELETE_FEST_EVENT_SUCCESS";
export const DELETE_FEST_EVENT_FAIL = "DELETE_FEST_EVENT_FAIL";



export const GET_CLUB_EVENTS_REQUEST = "GET_CLUB_EVENTS_REQUEST";
export const GET_CLUB_EVENTS_SUCCESS = "GET_CLUB_EVENTS_SUCCESS";
export const GET_CLUB_EVENTS_FAIL = "GET_CLUB_EVENTS_FAIL";

export const GET_USER_EVENTS_REQUEST = "GET_USER_EVENTS_REQUEST";
export const GET_USER_EVENTS_SUCCESS = "GET_USER_EVENTS_SUCCESS";
export const GET_USER_EVENTS_FAIL = "GET_USER_EVENTS_FAIL";



export const ALL_CLUB_GALLERY_REQUEST = "ALL_CLUB_GALLERY_REQUEST";
export const ALL_CLUB_GALLERY_SUCCESS = "ALL_CLUB_GALLERY_SUCCESS";
export const ALL_CLUB_GALLERY_FAIL = "ALL_CLUB_GALLERY_FAIL";

export const ALL_GALLERY_PHOTOS_REQUEST = "ALL_GALLERY_PHOTOS_REQUEST";
export const ALL_GALLERY_PHOTOS_SUCCESS = "ALL_GALLERY_PHOTOS_SUCCESS";
export const ALL_GALLERY_PHOTOS_FAIL = "ALL_GALLERY_PHOTOS_FAIL";

export const ADMIN_DELETE_GALLERY_PHOTOS_REQUEST = "ADMIN_DELETE_GALLERY_PHOTOS_REQUEST";
export const ADMIN_DELETE_GALLERY_PHOTOS_SUCCESS = "ADMIN_DELETE_GALLERY_PHOTOS_SUCCESS";
export const ADMIN_DELETE_GALLERY_PHOTOS_FAIL = "ADMIN_DELETE_GALLERY_PHOTOS_FAIL";


export const GET_ADMINISTRATION_TEAM_REQUEST = "GET_ADMINISTRATION_TEAM_REQUEST";
export const GET_ADMINISTRATION_TEAM_SUCCESS = "GET_ADMINISTRATION_TEAM_SUCCESS";
export const GET_ADMINISTRATION_TEAM_FAIL = "GET_ADMINISTRATION_TEAM_FAIL";

export const DELETE_ADMINISTRATION_TEAM_REQUEST = "DELETE_ADMINISTRATION_TEAM_REQUEST";
export const DELETE_ADMINISTRATION_TEAM_SUCCESS = "DELETE_ADMINISTRATION_TEAM_SUCCESS";
export const DELETE_ADMINISTRATION_TEAM_FAIL = "DELETE_ADMINISTRATION_TEAM_FAIL";



export const TOP_ANNOUNCEMENTS_REQUEST = "TOP_ANNOUNCEMENTS_REQUEST";
export const TOP_ANNOUNCEMENTS_SUCCESS = "TOP_ANNOUNCEMENTS_SUCCESS";
export const TOP_ANNOUNCEMENTS_FAIL = "TOP_ANNOUNCEMENTS_FAIL";

export const ALL_ANNOUNCEMENTS_REQUEST = "ALL_ANNOUNCEMENTS_REQUEST";
export const ALL_ANNOUNCEMENTS_SUCCESS = "ALL_ANNOUNCEMENTS_SUCCESS";
export const ALL_ANNOUNCEMENTS_FAIL = "ALL_ANNOUNCEMENTS_FAIL";

export const ADMIN_DELETE_ANNOUNCEMENT_REQUEST = "ADMIN_DELETE_ANNOUNCEMENT_REQUEST";
export const ADMIN_DELETE_ANNOUNCEMENT_SUCCESS = "ADMIN_DELETE_ANNOUNCEMENT_SUCCESS";
export const ADMIN_DELETE_ANNOUNCEMENT_FAIL = "ADMIN_DELETE_ANNOUNCEMENT_FAIL";

export const ALL_LETTERS_REQUEST = "ALL_LETTERS_REQUEST";
export const ALL_LETTERS_SUCCESS = "ALL_LETTERS_SUCCESS";
export const ALL_LETTERS_FAIL = "ALL_LETTERS_FAIL";

export const ADMIN_DELETE_LETTER_REQUEST = "ADMIN_DELETE_LETTER_REQUEST";
export const ADMIN_DELETE_LETTER_SUCCESS = "ADMIN_DELETE_LETTER_SUCCESS";
export const ADMIN_DELETE_LETTER_FAIL = "ADMIN_DELETE_LETTER_FAIL";


export const TOP_DONARS_REQUEST = "TOP_DONARS_REQUEST";
export const TOP_DONARS_SUCCESS = "TOP_DONARS_SUCCESS";
export const TOP_DONARS_FAIL = "TOP_DONARS_FAIL";

export const GET_ALL_DONARS_REQUEST = "GET_ALL_DONARS_REQUEST";
export const GET_ALL_DONARS_SUCCESS = "GET_ALL_DONARS_SUCCESS";
export const GET_ALL_DONARS_FAIL = "GET_ALL_DONARS_FAIL";


export const ADMIN_DELETE_DONAR_REQUEST = "ADMIN_DELETE_DONAR_REQUEST";
export const ADMIN_DELETE_DONAR_SUCCESS = "ADMIN_DELETE_DONAR_SUCCESS";
export const ADMIN_DELETE_DONAR_FAIL = "ADMIN_DELETE_DONAR_FAIL";


export const GET_ACADEMIC_BOOKS_REQUEST = "GET_ACADEMIC_BOOKS_REQUEST";
export const GET_ACADEMIC_BOOKS_SUCCESS = "GET_ACADEMIC_BOOKS_SUCCESS";
export const GET_ACADEMIC_BOOKS_FAIL = "GET_ACADEMIC_BOOKS_FAIL";

export const ADMIN_DELETE_ACADEMIC_BOOKS_REQUEST = "ADMIN_DELETE_ACADEMIC_BOOKS_REQUEST";
export const ADMIN_DELETE_ACADEMIC_BOOKS_SUCCESS = "ADMIN_DELETE_ACADEMIC_BOOKS_SUCCESS";
export const ADMIN_DELETE_ACADEMIC_BOOKS_FAIL = "ADMIN_DELETE_ACADEMIC_BOOKS_FAIL";


export const SIGN_IN_USER_REQUEST = "SIGN_IN_USER_REQUEST";
export const SIGN_IN_USER_SUCCESS = "SIGN_IN_USER_SUCCESS";
export const SIGN_IN_USER_FAIL = "SIGN_IN_USER_FAIL";

export const SIGN_UP_USER_REQUEST = "SIGN_UP_USER_REQUEST";
export const SIGN_UP_USER_SUCCESS = "SIGN_UP_USER_SUCCESS";
export const SIGN_UP_USER_FAIL = "SIGN_UP_USER_FAIL";

export const SIGNOUT_USER_REQUEST = "SIGNOUT_USER_REQUEST";
export const SIGNOUT_USER_SUCCESS = "SIGNOUT_USER_SUCCESS";
export const SIGNOUT_USER_FAIL = "SIGNOUT_USER_FAIL";

export const DELETE_CURRENT_USER_REQUEST = "DELETE_CURRENT_USER_REQUEST";
export const DELETE_CURRENT_USER_SUCCESS = "DELETE_CURRENT_USER_SUCCESS";
export const DELETE_CURRENT_USER_FAIL = "DELETE_CURRENT_USER_FAIL";

export const UPDATE_USER_PROFILE_REQUEST = "UPDATE_USER_PROFILE_REQUEST";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAIL = "UPDATE_USER_PROFILE_FAIL";

export const SET_IS_UPDATE_FALSE = "SET_IS_UPDATE_FALSE";

export const UPDATE_PROFILE_PASSWORD_REQUEST = "UPDATE_PROFILE_PASSWORD_REQUEST";
export const UPDATE_PROFILE_PASSWORD_SUCCESS = "UPDATE_PROFILE_PASSWORD_SUCCESS";
export const UPDATE_PROFILE_PASSWORD_FAIL = "UPDATE_PROFILE_PASSWORD_FAIL";

export const RESET_PASSWORD_TOKEN_GENERATE_REQUEST = "RESET_PASSWORD_TOKEN_GENERATE_REQUEST";
export const RESET_PASSWORD_TOKEN_GENERATE_SUCCESS = "RESET_PASSWORD_TOKEN_GENERATE_SUCCESS";
export const RESET_PASSWORD_TOKEN_GENERATE_FAIL = "RESET_PASSWORD_TOKEN_GENERATE_FAIL";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const GET_CURRENT_USER_REQUEST = "GET_CURRENT_USER_REQUEST";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";
export const GET_CURRENT_USER_FAIL = "GET_CURRENT_USER_FAIL";

export const GENERATE_ADMIN_REQUEST = "GENERATE_ADMIN_REQUEST";
export const GENERATE_ADMIN_SUCCESS = "GENERATE_ADMIN_SUCCESS";
export const GENERATE_ADMIN_FAIL = "GENERATE_ADMIN_FAIL";

export const ADMIN_SIGNUP_REQUEST = "ADMIN_SIGNUP_REQUEST";
export const ADMIN_SIGNUP_SUCCESS = "ADMIN_SIGNUP_SUCCESS";
export const ADMIN_SIGNUP_FAIL = "ADMIN_SIGNUP_FAIL";

export const ADMIN_GET_ALL_USERS_REQUEST = "ADMIN_GET_ALL_USERS_REQUEST";
export const ADMIN_GET_ALL_USERS_SUCCESS = "ADMIN_GET_ALL_USERS_SUCCESS";
export const ADMIN_GET_ALL_USERS_FAIL = "ADMIN_GET_ALL_USERS_FAIL";



export const SET_PREV_LOCATION_REQUEST = "SET_PREV_LOCATION_REQUEST";
export const SET_PREV_LOCATION_SUCCESS = "SET_PREV_LOCATION_SUCCESS";
export const SET_PREV_LOCATION_FAIL = "SET_PREV_LOCATION_FAIL";



export const GET_CAROUSEL_IMGS_REQUEST = "GET_CAROUSEL_IMGS_REQUEST";
export const GET_CAROUSEL_IMGS_SUCCESS = "GET_CAROUSEL_IMGS_SUCCESS";
export const GET_CAROUSEL_IMGS_FAIL = "GET_CAROUSEL_IMGS_FAIL";

export const DELETE_CAROUSEL_IMGS_REQUEST = "DELETE_CAROUSEL_IMGS_REQUEST";
export const DELETE_CAROUSEL_IMGS_SUCCESS = "DELETE_CAROUSEL_IMGS_SUCCESS";
export const DELETE_CAROUSEL_IMGS_FAIL = "DELETE_CAROUSEL_IMGS_FAIL";



export const SEND_CONTACT_MSG_REQUEST = "SEND_CONTACT_MSG_REQUEST";
export const SEND_CONTACT_MSG_SUCCESS = "SEND_CONTACT_MSG_SUCCESS";
export const SEND_CONTACT_MSG_FAIL = "SEND_CONTACT_MSG_FAIL";



export const GET_PAST_MEMBERS_REQUEST = "GET_PAST_MEMBERS_REQUEST";
export const GET_PAST_MEMBERS_SUCCESS = "GET_PAST_MEMBERS_SUCCESS";
export const GET_PAST_MEMBERS_FAIL = "GET_PAST_MEMBERS_FAIL";

export const DELETE_PAST_MEMBER_REQUEST = "DELETE_PAST_MEMBER_REQUEST";
export const DELETE_PAST_MEMBER_SUCCESS = "DELETE_PAST_MEMBER_SUCCESS";
export const DELETE_PAST_MEMBER_FAIL = "DELETE_PAST_MEMBER_FAIL";




export const CLEAR_ERRORS = "CLEAR_ERRORS";